Fix CircleCI config - attempt 4

diff --git a/.circleci/release b/.circleci/release
--- a/.circleci/release
+++ b/.circleci/release
@@ -1,6 +1,11 @@
 #!/bin/bash
 
-# Note: this clobbers any older releases with the same version...
+# Note: this clobbers any older releases with the same version.
+
+if [[ ! -v "$GITHUB_TOKEN" ]]; then
+    echo "GITHUB_TOKEN is not set. Aborting."
+    exit 1
+fi
 
 VERSION=$(make version)
 RELEASE_ARTIFACT="dist/bock-${VERSION}-py3-none-any.whl"
